### ISSUE TITLE
Implement kayboard navigation on the paddle.

### ISSUE THREAD

**Issue by amitsagtani97** [amitsagtani97/Classic-Arcade-Game#5]
At present the player paddle is controlled by mouse only, implement keyboard navigation on the paddle.

**Comment by nyreed** [comment]
Let me give this one a try.

**Comment by amitsagtani97** [comment]
@nyreed hi, if you are interested, give it a try :)

**Comment by raspberrry** [comment]
Hi, I'd like to attempt this

**Comment by amitsagtani97** [comment]
@raspberrry sure :)
