### ISSUE TITLE
Increase the speed of the ball after regular interval of time

### ISSUE THREAD

**Issue by amitsagtani97** [amitsagtani97/Classic-Arcade-Game#6]
Increase the speed of ball after some regular interval of time in order to increase the difficulty of  the game as time passes.

**Comment by Mojachieee** [comment]
I can do this.

**Comment by amitsagtani97** [comment]
@Mojachieee hi, if you are interested, you can proceed :)

**Comment by pierreericgarcia** [comment]
Hello @amitsagtani97 ! 😄 I love the code of your game ! It seems easy at first but then we understand all of the mechanism, it begins to become harder ahaha 😂 ! Just to say that I'm on it too 😏
